openapi: 3.0.0
info:
  title: Webhook Subscription API
  version: 1.0.0
paths:
  /massivetransaction/api/ext/v1/orgs/{organizationId}/webhook/subscriptions:
    post:
      summary: Registering Webhook URLs
      parameters:
        - name: organizationId
          in: path
          required: true
          description: ID of the organization
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: URL for the webhook
                  example: "https://my-webhook.com"
      responses:
        200:
          description: Webhook URL registered successfully
    get:
      summary: Verify your webhook URL registration
      parameters:
        - name: organizationId
          in: path
          required: true
          description: ID of the organization
          schema:
            type: string
      responses:
        200:
          description: Successfully retrieved webhook subscriptions
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                        referenceName:
                          type: string
                        url:
                          type: string
                  pageable:
                    type: object
                    properties: # specify other properties
                  last:
                    type: boolean
                  totalPages:
                    type: integer
                  totalElements:
                    type: integer
                  number:
                    type: integer
                  sort:
                    type: object
                    properties: # specify sort properties
                  size:
                    type: integer
                  first:
                    type: boolean
                  numberOfElements:
                    type: integer
                  empty:
                    type: boolean